### ISSUE TITLE
Running class based tasks does not pass 'self'

### ISSUE THREAD

**Issue by dbajpeyi** [celery/django-celery#258]
http://docs.celeryproject.org/en/latest/reference/celery.contrib.methods.html

Running any of the above examples throws a type error : 
        TypeError('add() takes exactly 3 arguments (2 given)',)

I use the command : 
        python manage.py celery -B -l INFO

Although this doesn't throw an error if I run it from the shell ,say : 
from app.tasks import *
        x = X()
        x.add.delay(2,2)

works fine.

Here is the full stack trace : 

[2013-07-14 14:38:21,000: ERROR/MainProcess] Task report.tasks.add[6b79e113-8f65-4d27-bded-9b2978672a65] raised exception: TypeError('add() takes exactly 3 arguments (2 given)',)
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 233, in trace_task
R = retval = fun(_args, *_kwargs)
File "/usr/local/lib/python2.7/dist-packages/celery/task/trace.py", line 420, in protected_call
return self.run(_args, *_kwargs)
None: add() takes exactly 3 arguments (2 given)

**Comment by iamit** [comment]
question for @Ask: you stated late 2013: 'Task methods are experimental and I have so much else to do, I will probably find a solution for it, but the best is to not use them for now as it's not a stable feature, more of a suggestion.'. 
Does this still aplly? I just switched to 3.1 because I had some problems with django-celery. I used class based tasks... but reading this... i tried to role back, ans use the class decorators... and the problem disapeared... because i both upgraded and switched from class based to decorators... not sure what solved my problems.... (and whether I should turn all my tasks back to using the class decorators).... I use the class based task, so I could extend a base custom class that does some logging in the database.... (nice if you use celery in django... to have all the info in the same webapp)

And a tip: not sure how many uses django-celery.... but the django-rest-framework developer (Tom Christie) got a nice budget to spend some extra time on this package from using crowd funding: https://www.kickstarter.com/projects/tomchristie/django-rest-framework-3

**Comment by robertsutherland** [comment]
@ask has this been fixed? Using celery 3.1 and am having a similar error when passing 'self' to class-based tasks.

**Comment by auvipy** [comment]
@robertsutherland it's me you should be bugging for django-celery

**Comment by jmhansen** [comment]
@alok15ee's suggestion worked for me.  I needed to add `filter=task_method` to my task decorator: `@app.task(filter=task_method)`.

See [Celery documentation here](http://docs.celeryproject.org/en/latest/reference/celery.contrib.methods.html).

**Comment by hustlibraco** [comment]
celery4 doesn't support task_method, how to solve thie problem with CELERY 4.0?

**Comment by NullYing** [comment]
I also want to know, how to solve thie problem with CELERY 4.0?

**Comment by newzubakhin** [comment]
Same issue.

**Comment by Tuke** [comment]
Same issue.

**Comment by auvipy** [comment]
using django celery beat and django result back end is the main solution. this package isn;t supported for celery 4 acatually
