### ISSUE TITLE
Celery beat DB sync problem 

### ISSUE THREAD

**Issue by sornalingam** [celery/django-celery#373]
I am using Djcelery in my application. I have the below settings 

app.conf.update(
    CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
)

I am using MS sql as DB store for Django.   

When i trigger my celery beat it is not Sync between DB and the application 

`max_interval  = 5 ` But the sync between DB and the celery beat is not happening after 5 sec. 

When i run the beat i am seeing below message  and hangs like this, 

' maxinterval -> now (0s)
[2015-05-11 09:39:25,464: INFO/MainProcess] beat: Starting...
[2015-05-11 09:39:25,464: INFO/MainProcess] Writing entries...'

What went wrong in this ?  Why the Sync between DB and celery beat is not happening after 5 sec ? 

Thanks

**Comment by kaixi** [comment]
Hi, I use django-celery to create cron tasks programmatically and this was a major pain for me as well, because it's not documented anywhere.

Here's how I solved it:

After scheduling my celery job, you must update the `last_update` field of the db entry in the `PeriodicTasks` table.

My use case involves executing celery jobs on a model save, so I found that the most convenient way to trigger the sync automatically is by creating a receiver function that listens to the Django model `post_save` signal.

Here's the code:
```py
import datetime
from django.dispatch import receiver
from django.db.models.signals import post_save
from djcelery.models import PeriodicTasks

@receiver(post_save)
def trigger_celerybeat_sync(sender, **kwargs):
    PeriodicTasks.objects.update(last_update=datetime.datetime.now())
```

Good luck and may the force be with you :)
